[package]
name = "tsm-ipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
zmq = "0.10.0"
protobuf = "3.2.0"

[build-dependencies]
protobuf-codegen = "3.2.0"

