[application]
log_level = "debug"

[watchdog]
enabled = true
timeout_s = 10

[[units]]
name = "foo"
executable = "ls"
arguments = [ "-l", "-a" ]
dependencies = []
restart_policy = "always" # implies that watchdog events must be sent by the executable
user = "" # default. If empty, the user of the current process is used
group = "" # default. If empty, the group of the current process is used
enabled = true # default

[[units]]
name = "bar"
executable = "ps"
arguments = [ "-aux" ]
dependencies = [ "foo" ]
restart_policy = "never" # run once, no watchdog events are expected
user = "" # default. If empty, the user of the current process is used
group = "" # default. If empty, the group of the current process is used
enabled = true # default