[application]
log_level = "debug" # Optional. Defaults to "info". Possible values: "debug", "info", "warn", "error"

[[units]]
name = "foo"                            # Mandatory
executable = "sleep"                    # Mandatory
arguments = [ "10" ]                    # Optional. Defaults to empty list.
dependencies = []                       # Optional. Defaults to empty list.
restart_policy = "always"               # Optional. Defaults to "always". Possible values: "always", "never".
user = ""                               # Optional. Defaults to current user.
group = ""                              # Optional. Defaults to current group.
enabled = true                          # Optional. Defaults to true.
startup_probe.executable = "ls"         # Optional. Defaults to empty string.
startup_probe.arguments = ["/tmp"]      # Optional. Defaults to empty list.
startup_probe.interval_s = 5            # Optional. Defaults to 60.
startup_probe.timeout_s = 5             # Optional. Defaults to 10.
readiness_probe.executable = "ls"       # Optional. Defaults to empty string.
readiness_probe.arguments = ["/tmp"]    # Optional. Defaults to empty list.
readiness_probe.interval_s = 5          # Optional. Defaults to 60.
readiness_probe.timeout_s = 5           # Optional. Defaults to 10.
liveness_probe.executable = "ls"        # Optional. Defaults to empty string.
liveness_probe.arguments = ["/tmp"]     # Optional. Defaults to empty list.
liveness_probe.interval_s = 5           # Optional. Defaults to 60.
liveness_probe.timeout_s = 5            # Optional. Defaults to 10.

[[units]]
name = "bar"                            # Mandatory
executable = "ps"                       # Mandatory
arguments = [ "aux" ]                   # Optional. Defaults to empty list.
dependencies = []                       # Optional. Defaults to empty list.
restart_policy = "never"                # Optional. Defaults to "always". Possible values: "always", "never".
user = ""                               # Optional. Defaults to current user.
group = ""                              # Optional. Defaults to current group.
enabled = true                          # Optional. Defaults to true.
startup_probe.executable = "ls"         # Optional. Defaults to empty string.
startup_probe.arguments = ["/tmp"]      # Optional. Defaults to empty list.
startup_probe.interval_s = 5            # Optional. Defaults to 60.
startup_probe.timeout_s = 5             # Optional. Defaults to 10.
readiness_probe.executable = "ls"       # Optional. Defaults to empty string.
readiness_probe.arguments = ["/tmp"]    # Optional. Defaults to empty list.
readiness_probe.interval_s = 5          # Optional. Defaults to 60.
readiness_probe.timeout_s = 5           # Optional. Defaults to 10.
liveness_probe.executable = "ls"        # Optional. Defaults to empty string.
liveness_probe.arguments = ["/tmp"]     # Optional. Defaults to empty list.
liveness_probe.interval_s = 5           # Optional. Defaults to 60.
liveness_probe.timeout_s = 5            # Optional. Defaults to 10.