[application]
log_level = "trace" # Optional. Defaults to "info". Possible values: "debug", "info", "warn", "error", "trace".

[[units]]
name = "foo"                            # Mandatory
executable = "sleep"                    # Mandatory
arguments = [ "10" ]                    # Optional. Defaults to empty list.
dependencies = []                       # Optional. Defaults to empty list.
restart_policy = "always"               # Optional. Defaults to "always". Possible values: "always", "never".
user = ""                               # Optional. Defaults to current user.
group = ""                              # Optional. Defaults to current group.
enabled = true                          # Optional. Defaults to true.
liveness_probe.executable = "ls"        # Optional. Defaults to empty string.
liveness_probe.arguments = ["/tmp"]     # Optional. Defaults to empty list.
liveness_probe.interval_s = 5           # Optional. Defaults to 60.
liveness_probe.timeout_s = 5            # Optional. Defaults to 10.

[[units]]
name = "bar"                            # Mandatory
executable = "ls"                       # Mandatory
arguments = [ "-lah" ]                  # Optional. Defaults to empty list.
dependencies = []                       # Optional. Defaults to empty list.
restart_policy = "never"                # Optional. Defaults to "always". Possible values: "always", "never".
user = ""                               # Optional. Defaults to current user.
group = ""                              # Optional. Defaults to current group.
enabled = true                          # Optional. Defaults to true.
liveness_probe.executable = "ls"        # Optional. Defaults to empty string.
liveness_probe.arguments = ["/tmp"]     # Optional. Defaults to empty list.
liveness_probe.interval_s = 5           # Optional. Defaults to 60.
liveness_probe.timeout_s = 5            # Optional. Defaults to 10.
