[application]
log_level = "debug" # Optional. Defaults to "info". Possible values: "debug", "info", "warn", "error"

[[units]]
name = "foo" # Mandatory
executable = "sleep" # Mandatory
arguments = [ "10" ] # Optional. Defaults to empty list.
dependencies = [] # Optional. Defaults to empty list.
restart_policy = "always" # Optional. Defaults to "always". Possible values: "always", "never".
user = "" # Optional. If empty or unset, the user of the current process is used
group = "" # Optional. If empty or unset, the group of the current process is used
enabled = true # Optional. Defaults to true.
startup_probe.command = ["ls", "/tmp"] # defaults to empty list
readiness_probe.command = ["ls", "/tmp"] # defaults to empty list
liveness_probe.command = ["ls", "/tmp"] # defaults to empty list
liveness_probe.interval_s = 5 # defaults to 60

[[units]]
name = "bar" # Mandatory
executable = "ps" # Mandatory
arguments = [ "aux" ] # Optional. Defaults to empty list.
dependencies = [] # Optional. Defaults to empty list.
restart_policy = "never" # Optional. Defaults to "always". Possible values: "always", "never".
user = "" # Optional. If empty or unset, the user of the current process is used
group = "" # Optional. If empty or unset, the group of the current process is used
enabled = true # Optional. Defaults to true.
startup_probe.command = ["ls", "/tmp"] # defaults to empty list
readiness_probe.command = ["ls", "/tmp"] # defaults to empty list
liveness_probe.command = ["ls", "/tmp"] # defaults to empty list
liveness_probe.interval_s = 5 # defaults to 60