[package]
name = "tsm-unitman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.29.2"

[dev-dependencies]


[profile.release]
strip = "debuginfo"